/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.db;

/**
 *
 * @author Lasitha Ranawaka
 */
public class Booking_details extends javax.swing.JDialog {

    /**
     * Creates new form template
     */
    public Booking_details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel3.setText(com.currentdate.getselected_calenderdate);
        jLabel4.setText(com.currentdate.time_duration);
        loadtbl();
        txt_admisson_no.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbook = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txt_admisson_no = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Booking Details");
        jLabel1.setOpaque(true);

        tblbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Admission No", "Name", "TP"
            }
        ));
        tblbook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblbookKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblbook);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txt_admisson_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_admisson_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_admisson_noActionPerformed(evt);
            }
        });
        txt_admisson_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_admisson_noKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enter Admission No");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_admisson_no, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_admisson_no, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("Date");

        jLabel7.setText("Time range");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        booking();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblbookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblbookKeyPressed
        if (evt.getKeyCode() == 127) {
            int a = JOptionPane.showConfirmDialog(null, "Are your sure to Delete this Booking?", "Warning", 0);
            if (a == JOptionPane.YES_OPTION) {
                try {
                    int rowid = tblbook.getSelectedRow();
                    String booking_id = tblbook.getValueAt(rowid, 0).toString();
                    model.db.putData("delete from booking where id='" + booking_id + "'");
                    jLabel5.setText("Deleted Subject from Database!!!");
                    jLabel5.setForeground(Color.red);
                    loadtbl();

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }
    }//GEN-LAST:event_tblbookKeyPressed

    private void txt_admisson_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_admisson_noKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_admisson_noKeyPressed

    private void txt_admisson_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_admisson_noActionPerformed
        booking();
    }//GEN-LAST:event_txt_admisson_noActionPerformed
    String one = "1";
    String two = "2";
    String three = "3";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booking_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booking_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booking_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booking_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Booking_details dialog = new Booking_details(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbook;
    private javax.swing.JTextField txt_admisson_no;
    // End of variables declaration//GEN-END:variables

    private boolean isALreadyExistadmission() {
        boolean bol = false;
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "customer_register.admission_no\n"
                    + "FROM\n"
                    + "customer_register\n"
                    + "WHERE\n"
                    + "customer_register.admission_no = '" + txt_admisson_no.getText() + "'");
            if (rs.next()) {
//                practical_topic_id = rs.getInt(2);
//                com.Messages.normaljoption("practical_topic_id " + practical_topic_id);
                bol = true;
//                Messages.errorjoption("This NIC Number Already Exist ! ");
//                txtnic.grabFocus();
//                txtnic.selectAll();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return bol;
    }

    private void loadtbl() {
        DefaultTableModel dtm = (DefaultTableModel) tblbook.getModel();
        dtm.setRowCount(0);

        try {
            ResultSet rs = db.getData("SELECT\n"
                    + "booking.id,\n"
                    + "booking.admission_no,\n"
                    + "customer_register.tp1,\n"
                    + "uniquecustomerdetails.namewithinitial\n"
                    + "FROM\n"
                    + "booking ,\n"
                    + "customer_register ,\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "booking.customer_register_id = customer_register.id AND\n"
                    + "customer_register.uniqueCustomerDetails_id = uniquecustomerdetails.id AND\n"
                    + "booking.date = '" + jLabel3.getText() + "' AND\n"
                    + "booking.time = '" + jLabel4.getText() + "'");

            while (rs.next()) {
                String id = rs.getString(1);
                String admission = rs.getString(2);
                String tp = rs.getString(3);
                String name = rs.getString(4);

                Object arr[] = {id, admission, name, tp};
                dtm.addRow(arr);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void booking() {
        if (txt_admisson_no.getText().isEmpty()) {
            jLabel5.setText("Please enter your admission number!");
            jLabel5.setForeground(Color.red);
            txt_admisson_no.grabFocus();

        } else {
            int cus_id = 0;
            try {
                ResultSet rs = db.getData("SELECT\n"
                        + "customer_register.id\n"
                        + "FROM\n"
                        + "customer_register\n"
                        + "WHERE\n"
                        + "customer_register.admission_no = '" + txt_admisson_no.getText() + "'");

                if (rs.next()) {
                    cus_id = rs.getInt(1);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            if (isALreadyExistadmission()) {
                if (!isALreadyExistadmission_inBooking()) {

                    try {
                        db.putData("INSERT INTO booking (date,time,admission_no,status,customer_register_id)"
                                + "values('" + jLabel3.getText().trim() + "','" + jLabel4.getText().trim() + "',"
                                + "'" + txt_admisson_no.getText().trim() + "','0','" + cus_id + "')");

                        jLabel5.setText("Date is booked!");
                        jLabel5.setForeground(Color.GREEN);
                        txt_admisson_no.setText("");
                        loadtbl();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } else {
                    jLabel5.setText("Alraedy Exist this admission! ");
                    jLabel5.setForeground(Color.red);

                }

            } else {
                jLabel5.setText("There is no admission no like this!");
                jLabel5.setForeground(Color.red);

            }

        }
    }

    private boolean isALreadyExistadmission_inBooking() {
        boolean bol = false;
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "booking.admission_no,\n"
                    + "booking.date,\n"
                    + "booking.time\n"
                    + "FROM\n"
                    + "booking\n"
                    + "WHERE\n"
                    + "booking.admission_no = '"+txt_admisson_no.getText()+"' AND\n"
                    + "booking.date = '"+jLabel3.getText()+"' AND\n"
                    + "booking.time = '"+jLabel4.getText()+"'");
            if (rs.next()) {
//                practical_topic_id = rs.getInt(2);
//                com.Messages.normaljoption("practical_topic_id " + practical_topic_id);
                bol = true;
//                Messages.errorjoption("This NIC Number Already Exist ! ");
//                txtnic.grabFocus();
//                txtnic.selectAll();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return bol;
    }
}
