/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import com.Messages;
import com.userstatus;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.db2;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Lasitha Ranawaka
 */
public class customerRegister extends javax.swing.JDialog {

    /**
     * Creates new form template
     */
    public customerRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon img = new ImageIcon("src/png/desktop.png");
        this.setIconImage(img.getImage());
        loadadmissiono();
        loadcmbdivision();
        loadpolice();

    }

    int id = 0;
    String sex = "";
    String canDriveOrNot = "";
    String manualOrAuto = "";
    int uniqueCustomerDetails_id;
    int customerId;
    int uniqueid;
    int divisionId = 0;
    int policeId = 0;

    customerRegister(String adno, boolean b) {

        initComponents();
        ImageIcon img = new ImageIcon("src/png/desktop.png");
        this.setIconImage(img.getImage());
        txtfindadmission.setText(adno);
        txtadmissiono.setText(adno);
        loaddetailsforadmissionno();
        loadcmbdivision();
        loadpolice();
        //  loadadmissiono();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnic = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdob = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmedicalno = new javax.swing.JFormattedTextField();
        cmbcancantdrive = new javax.swing.JComboBox();
        cmbmanualauto2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtadmissiono = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtbarcode = new javax.swing.JFormattedTextField();
        txttp1 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttp2 = new javax.swing.JFormattedTextField();
        txtadress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttp3 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtvehicleclass = new javax.swing.JFormattedTextField();
        cmbSex = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        txtnamewithinitials = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtlicenno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtlicendate = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtlicenvclass = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtfindadmission = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDivisionalSecretariat = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtpolice = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Register(Updates  and searching Only)");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Details"));

        jLabel2.setText("Nic");

        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnicKeyPressed(evt);
            }
        });

        jLabel3.setText("Name");

        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });

        jLabel4.setText("DOB");

        try {
            txtdob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdob.setText("0000-00-00");
        txtdob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdobKeyPressed(evt);
            }
        });

        jLabel5.setText("Sex");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText("Select");

        jLabel20.setText("Gear");

        jLabel15.setText("Medical No");

        txtmedicalno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmedicalnoKeyPressed(evt);
            }
        });

        cmbcancantdrive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cannot Drive", "Can Drive" }));
        cmbcancantdrive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbcancantdriveKeyPressed(evt);
            }
        });

        cmbmanualauto2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Auto" }));
        cmbmanualauto2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbmanualauto2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbcancantdrive, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmanualauto2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmbcancantdrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbmanualauto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtmedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel7.setText("Admission No");

        txtadmissiono.setEditable(false);

        jLabel12.setText("Barcode");

        txtbarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarcodeKeyPressed(evt);
            }
        });

        try {
            txttp1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttp1.setText("000-0000000");
        txttp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttp1KeyPressed(evt);
            }
        });

        jLabel9.setText("Tp1");

        jLabel10.setText("Tp2");

        try {
            txttp2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttp2KeyPressed(evt);
            }
        });

        txtadress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtadressKeyPressed(evt);
            }
        });

        jLabel8.setText("Adress");

        jLabel11.setText("Tp3");

        try {
            txttp3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttp3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttp3KeyPressed(evt);
            }
        });

        jLabel14.setText("Vehicle Class");

        txtvehicleclass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvehicleclassKeyPressed(evt);
            }
        });

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cmbSex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbSexKeyPressed(evt);
            }
        });

        jLabel22.setText("Name With Initials");

        txtnamewithinitials.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamewithinitialsKeyPressed(evt);
            }
        });

        jLabel23.setText("Note");

        txtNote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtadmissiono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNote))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel22)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtnamewithinitials, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel4))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtvehicleclass, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttp1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttp2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txttp3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 48, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtadmissiono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(txtbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtNote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtnamewithinitials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txttp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txttp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txttp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtvehicleclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtlicenno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicennoKeyPressed(evt);
            }
        });

        jLabel16.setText("Old Licence  No");

        try {
            txtlicendate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtlicendate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicendateKeyPressed(evt);
            }
        });

        jLabel18.setText("Vehicle Class");

        jLabel17.setText("Licen Date");

        txtlicenvclass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicenvclassKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtlicenno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtlicendate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtlicenvclass, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtlicenno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtlicendate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtlicenvclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Search by Admission No");

        txtfindadmission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfindadmissionActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Find");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Add Written Exam Detals");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Add Practical Exam Detals");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Print use only", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(0, 255, 0))); // NOI18N

        jLabel13.setText("Divisional Secretariat :");

        txtDivisionalSecretariat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDivisionalSecretariatKeyPressed(evt);
            }
        });

        jLabel21.setText("Police station");

        txtpolice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpoliceKeyPressed(evt);
            }
        });

        jButton6.setText("R");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("New");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("R");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("New");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDivisionalSecretariat, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(txtpolice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtDivisionalSecretariat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(txtpolice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(253, 253, 253)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtfindadmission, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtfindadmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jButton5)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean bol = true;

//canDriveOrNot
//        if (rbtncandrive.isSelected()) {
//            canDriveOrNot = "Can Drive";
//        } else if (rbtncantdrive.isSelected()) {
//            canDriveOrNot = "Cannot Drive";
//        }
        ///////////////////////////////////////////////////////////////////////////////////
        //manualOrAuto
//        if (rbtnmanual.isSelected()) {
//            manualOrAuto = "Manual";
//        } else if (rbtnauto.isSelected()) {
//            manualOrAuto = "Auto";
//        }
        ///////////////////////////////////////////////////////////////////////////////////////
        //male female
//        if (rbtnmale.isSelected()) {
//            sex = "Male";
//
//        } else if (rbtnfemale.isSelected()) {
//            sex = "Female";
//        }
        ///////////////////////////////////////////////////////////////////////////////////////
        //get uniqueCustomerDetails_id
        try {
            ResultSet rs = model.db.getData("SELECT MAX(id) FROM uniquecustomerdetails");

            if (rs.next()) {
                uniqueCustomerDetails_id = rs.getInt(1);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        ////////////////////////////////////////////////////////////////////////////////////////

        if (txtnic.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the NIC!");
            txtnic.grabFocus();
            return;

        } else {
//            if (id == 0) {
//                try {
//                    //unique details send
//                    model.db.putData("INSERT INTO uniquecustomerdetails(nic,name,dob,sex,status)values('" + txtnic.getText() + "',"
//                            + "'" + txtname.getText() + "','" + txtdob.getText() + "','" + sex + "','" + "New" + "')");
//
//                    ////////////////////////////////
//                    //repeat data
//                    model.db.putData("INSERT INTO customer_register(uniqueCustomerDetails_id,admission_no,adress,tp1,tp2,tp3,"
//                            + "barcode,reg_date,vehicle_class,medicalNo,licenNo,licenDate,vclass,canDriveOrNot,manualOrAuto,"
//                            + "status)values('" + uniqueCustomerDetails_id + "','" + customerId + "','" + txtadress.getText() + "',"
//                            + "'" + txttp1.getText() + "','" + txttp2.getText() + "','" + txttp3.getText() + "','" + txtbarcode.getText() + "',"
//                            + " NOW(),'" + txtvehicleclass.getText() + "','" + txtmedicalno.getText() + "','" + txtlicenno.getText() + "',"
//                            + "'" + txtlicendate.getText() + "','" + txtlicenvclass.getText() + "','" + canDriveOrNot + "',"
//                            + "'" + manualOrAuto + "','" + "new" + "')");
//
//                    ///////////////////////////////////////////
//                    //log
//                    model.db.putData("INSERT INTO log(date,description,username)values(NOW(),'" + "new user register" + "',"
//                            + "'" + userstatus.LodUser + "')");
//
//                    ////////////////////////////////////////////////////////////////////////
//                    Messages.normaljoption("Data Saved!");
//                } catch (SQLException ex) {
//                    ex.printStackTrace();
//                }
//            } else {

            int idunique = 0;
            try {
                ResultSet rs = model.db.getData("SELECT\n"
                        + "uniquecustomerdetails.id\n"
                        + "FROM\n"
                        + "uniquecustomerdetails\n"
                        + "INNER JOIN customer_register ON uniquecustomerdetails.id = customer_register.uniqueCustomerDetails_id\n"
                        + "WHERE\n"
                        + "customer_register.admission_no = '" + txtadmissiono.getText() + "'");
                if (rs.next()) {
                    idunique = rs.getInt(1);

                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            /////////////////////division id////////////////////////////////
            try {
                ResultSet rs = model.db.getData("SELECT\n"
                        + "division.id\n"
                        + "FROM\n"
                        + "division\n"
                        + "WHERE\n"
                        + "division.division = '" + txtDivisionalSecretariat.getText() + "'");
                if (rs.next()) {
                    divisionId = rs.getInt(1);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            //////////////////////end division id///////////////////////
            ////////////////////get police id/////////////////////////
            try {
                ResultSet rs = model.db.getData("SELECT\n"
                        + "police.id\n"
                        + "FROM\n"
                        + "police\n"
                        + "WHERE\n"
                        + "police.police = '" + txtpolice.getText() + "'");
                if (rs.next()) {
                    policeId = rs.getInt(1);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            //////////////////end police id////////////////////////
            Connection con = db2.getconn();
            try {

                //repeat data
                model.db.putData("UPDATE  customer_register set adress='" + txtadress.getText() + "',"
                        + "tp1='" + txttp1.getText() + "',tp2='" + txttp2.getText() + "',tp3='" + txttp3.getText() + "',"
                        + "barcode='" + txtbarcode.getText() + "',vehicle_class='" + txtvehicleclass.getText() + "',"
                        + "medicalNo='" + txtmedicalno.getText() + "',licenNo='" + txtlicenno.getText() + "',"
                        + "licenDate='" + txtlicendate.getText() + "',vclass='" + txtlicenvclass.getText() + "',"
                        + "canDriveOrNot='" + cmbcancantdrive.getSelectedItem() + "',manualOrAuto='" + cmbmanualauto2.getSelectedItem() + "',"
                        + "status='" + "Updated" + "',division_id='" + divisionId + "',police_id='" + policeId + "',note='"+txtNote.getText()+"',nic='"+txtnic.getText()+"'  WHERE admission_no='" + txtadmissiono.getText() + "' ");
                if (con != null) {
                    con.commit();

                }
                ///////////////////////////////////////////
                //unique details send
                model.db.putData("UPDATE  uniquecustomerdetails set dob='" + txtdob.getText() + "',"
                        + "nic='" + txtnic.getText() + "',name='" + txtname.getText() + "',namewithinitial='" + txtnamewithinitials.getText() + "',sex='" + cmbSex.getSelectedItem() + "', status='" + "Updated" + "'"
                        + " WHERE id='" + idunique + "'");

                ////////////////////////////////
                //log
                model.db.putData("INSERT INTO log(date,description,username)values(NOW(),'" + "Customer Updated" + "',"
                        + "'" + userstatus.LodUser + "')");

                if (con != null) {
                    con.commit();

                }

                ////////////////////////////////////////////////////////////////////////
                Messages.normaljoption("Data Updated!");
            } catch (SQLException ex) {

                try {
                    bol = false;
                    com.Messages.warningjoption("Please Check Again! ");
                    //  db2.getconn().rollback();
                    System.out.println("rollbacked");
                    con.rollback();
                } catch (SQLException ex1) {
                    Logger.getLogger(customerRegister.class.getName()).log(Level.SEVERE, null, ex1);
                }
                ex.printStackTrace();
            }

        }

        // }
        if (bol) {

            new downPayment(txtadmissiono.getText()).setVisible(true);
            this.dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyPressed
        if (evt.getKeyCode() == 10) {
            if (isNotIDAlreadyExistInDB()) {
                txtbarcode.grabFocus();

            }
            loaddetails();

        }
    }//GEN-LAST:event_txtnicKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        loaddetailsforadmissionno();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtfindadmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfindadmissionActionPerformed
        loaddetailsforadmissionno();
    }//GEN-LAST:event_txtfindadmissionActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String adno = txtadmissiono.getText();
        String name = txtname.getText();

        new writtenExamDetails(adno, name, id, false).setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String adno = txtadmissiono.getText();
        String name = txtname.getText();

        new practicalExamDetails(adno, name, id, false).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            //JRTableModelDataSource dataSource;
            // dataSource = new JRTableModelDataSource(tbl_Gin.getModel());
            //String reportSource = "c:\\reports\\viewInvoice.jrxml";
            String reportSource = "src/reports/application.jrxml";
            Map<String, Object> params = new HashMap<String, Object>();

            params.put("nic", String.valueOf(txtnic.getText()));
            params.put("name", String.valueOf(txtname.getText()));
            params.put("dob", String.valueOf(txtdob.getText()));

            params.put("sex", String.valueOf(cmbSex.getSelectedItem()));
            params.put("adress", String.valueOf(txtadress.getText()));
            params.put("vclass", String.valueOf(txtvehicleclass.getText()));
            params.put("divisionals", String.valueOf(txtDivisionalSecretariat.getText()));
            params.put("police", String.valueOf(txtpolice.getText()));
            params.put("oldlicenNO", String.valueOf(txtlicenno.getText()));
            params.put("oldlicenIssuedate", String.valueOf(txtlicendate.getText()));
            params.put("oldlicenceVclass", String.valueOf(txtlicenvclass.getText()));
            params.put("admissionno", String.valueOf(txtadmissiono.getText()));

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params);

            JasperViewer.viewReport(jasperPrint, false);

            // JasperPrintManager.printReport(jasperPrint, false);
            // this.dispose();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtmedicalnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedicalnoKeyPressed
        if (evt.getKeyCode() == 10) {
            txtlicenno.grabFocus();

        }
    }//GEN-LAST:event_txtmedicalnoKeyPressed

    private void txtbarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarcodeKeyPressed
        if (evt.getKeyCode() == 10) {
            txtNote.grabFocus();

        }
    }//GEN-LAST:event_txtbarcodeKeyPressed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtname.getText();
            String result = changecase.toUpperCase();
            txtname.setText(result);
            txtnamewithinitials.grabFocus();

        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtdobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdobKeyPressed
        if (evt.getKeyCode() == 10) {
            cmbSex.grabFocus();

        }
    }//GEN-LAST:event_txtdobKeyPressed

    private void txtadressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadressKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtadress.getText();
            String result = changecase.toUpperCase();
            txtadress.setText(result);
            txttp1.grabFocus();

        }
    }//GEN-LAST:event_txtadressKeyPressed

    private void txttp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttp1KeyPressed
        if (evt.getKeyCode() == 10) {
            txttp2.grabFocus();

        }
    }//GEN-LAST:event_txttp1KeyPressed

    private void txttp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttp2KeyPressed
        if (evt.getKeyCode() == 10) {
            txttp3.grabFocus();

        }
    }//GEN-LAST:event_txttp2KeyPressed

    private void txttp3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttp3KeyPressed
        if (evt.getKeyCode() == 10) {
            txtvehicleclass.grabFocus();

        }
    }//GEN-LAST:event_txttp3KeyPressed

    private void txtlicennoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicennoKeyPressed
        if (evt.getKeyCode() == 10) {
            txtlicendate.grabFocus();

        }
    }//GEN-LAST:event_txtlicennoKeyPressed

    private void txtlicendateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicendateKeyPressed
        if (evt.getKeyCode() == 10) {
            txtlicenvclass.grabFocus();

        }
    }//GEN-LAST:event_txtlicendateKeyPressed

    private void txtlicenvclassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenvclassKeyPressed

        if (evt.getKeyCode() == 10) {
            String changecase = txtlicenvclass.getText();
            String result = changecase.toUpperCase();
            txtlicenvclass.setText(result);

            txtDivisionalSecretariat.grabFocus();

        }
    }//GEN-LAST:event_txtlicenvclassKeyPressed

    private void txtvehicleclassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehicleclassKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtvehicleclass.getText();
            String result = changecase.toUpperCase();
            txtvehicleclass.setText(result);
            cmbcancantdrive.grabFocus();

        }
    }//GEN-LAST:event_txtvehicleclassKeyPressed

    private void txtDivisionalSecretariatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDivisionalSecretariatKeyPressed
        if (evt.getKeyCode() == 10) {
            txtpolice.grabFocus();
        }
    }//GEN-LAST:event_txtDivisionalSecretariatKeyPressed

    private void txtpoliceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpoliceKeyPressed
        if (evt.getKeyCode() == 10) {
            jButton1.grabFocus();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoliceKeyPressed

    private void cmbSexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbSexKeyPressed
        if (evt.getKeyCode() == 10) {
            txtadress.grabFocus();

        }
    }//GEN-LAST:event_cmbSexKeyPressed

    private void cmbcancantdriveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbcancantdriveKeyPressed
        if (evt.getKeyCode() == 10) {
            cmbmanualauto2.grabFocus();

        }
    }//GEN-LAST:event_cmbcancantdriveKeyPressed

    private void cmbmanualauto2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbmanualauto2KeyPressed
        if (evt.getKeyCode() == 10) {
            txtmedicalno.grabFocus();

        }
    }//GEN-LAST:event_cmbmanualauto2KeyPressed

    private void txtnamewithinitialsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamewithinitialsKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtnamewithinitials.getText();
            String result = changecase.toUpperCase();
            txtnamewithinitials.setText(result);
            txtdob.grabFocus();

        }
    }//GEN-LAST:event_txtnamewithinitialsKeyPressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        loadcmbdivision();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new division(null, false).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        loadpolice();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        new police(null, false).setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtNoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoteKeyPressed
         if (evt.getKeyCode() == 10) {
            txtname.grabFocus();

        }
    }//GEN-LAST:event_txtNoteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                customerRegister dialog = new customerRegister(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cmbSex;
    private javax.swing.JComboBox cmbcancantdrive;
    private javax.swing.JComboBox cmbmanualauto2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtDivisionalSecretariat;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtadmissiono;
    private javax.swing.JTextField txtadress;
    private javax.swing.JFormattedTextField txtbarcode;
    private javax.swing.JFormattedTextField txtdob;
    private javax.swing.JTextField txtfindadmission;
    private javax.swing.JFormattedTextField txtlicendate;
    private javax.swing.JTextField txtlicenno;
    private javax.swing.JFormattedTextField txtlicenvclass;
    private javax.swing.JFormattedTextField txtmedicalno;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnamewithinitials;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpolice;
    private javax.swing.JFormattedTextField txttp1;
    private javax.swing.JFormattedTextField txttp2;
    private javax.swing.JFormattedTextField txttp3;
    private javax.swing.JFormattedTextField txtvehicleclass;
    // End of variables declaration//GEN-END:variables

    private void loadadmissiono() {
        //get id for admission no from customer register
        try {
            ResultSet rs = model.db.getData("SELECT MAX(id) FROM customer_register");
            if (rs.next()) {
                int i = rs.getInt(1);
                txtadmissiono.setText(String.valueOf(i + 5000));
                customerId = i + 5000;
                System.out.println(customerId);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        ///////////////////////////////////////////////////////////////////////////////////
    }

    private boolean isNotIDAlreadyExistInDB() {
        boolean bol = true;
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "uniquecustomerdetails.nic\n"
                    + "FROM\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "uniquecustomerdetails.nic = '" + txtnic.getText() + "'");
            if (rs.next()) {
                bol = false;
                Messages.errorjoption("This NIC Number Already Exist ! ");
                txtnic.grabFocus();
                txtnic.selectAll();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return bol;
    }

    private void loaddetails() {
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "uniquecustomerdetails.id,\n"
                    + "uniquecustomerdetails.nic,\n"
                    + "uniquecustomerdetails.`name`,\n"
                    + "uniquecustomerdetails.dob,\n"
                    + "uniquecustomerdetails.sex,\n"
                    + "uniquecustomerdetails.`status`,\n"
                    + "uniquecustomerdetails.namewithinitial\n"
                    + "FROM\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "uniquecustomerdetails.nic = '" + txtnic.getText() + "'");
            if (rs.next()) {
                id = rs.getInt(1);
                txtname.setText(rs.getString(3));
                txtdob.setText(rs.getString(4));
                cmbSex.setSelectedItem(rs.getString(5));
                txtnamewithinitials.setText(rs.getString(6));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loaddetailsforadmissionno() {
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "customer_register.id,\n"//1
                    + "customer_register.uniqueCustomerDetails_id,\n"//2
                    + "customer_register.admission_no,\n"//3
                    + "customer_register.adress,\n"//4
                    + "customer_register.tp1,\n"//5
                    + "customer_register.tp2,\n"//6
                    + "customer_register.tp3,\n"//7
                    + "customer_register.barcode,\n"//8
                    + "customer_register.reg_date,\n"//9
                    + "customer_register.vehicle_class,\n"//10
                    + "customer_register.medicalNo,\n"//11
                    + "customer_register.licenNo,\n"//12
                    + "customer_register.licenDate,\n"//13
                    + "customer_register.vclass,\n"//14
                    + "customer_register.canDriveOrNot,\n"//15
                    + "customer_register.manualOrAuto,\n"//16
                    + "customer_register.`status`,\n"//17
                    + "customer_register.nic,\n"//18
                    + "uniquecustomerdetails.id,\n"//19
                    + "uniquecustomerdetails.`name`,\n"//20
                    + "uniquecustomerdetails.dob,\n"//21
                    + "uniquecustomerdetails.sex,\n"//22
                    + "uniquecustomerdetails.`status`,\n"//23
                    + "uniquecustomerdetails.namewithinitial,\n"//24
                    + "customer_register.note\n"//25
                    + "FROM\n"
                    + "customer_register ,\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "customer_register.nic = uniquecustomerdetails.nic AND\n"
                    + "customer_register.admission_no = '" + txtfindadmission.getText() + "'");
            if (rs.next()) {
                id = rs.getInt(1);
                txtadmissiono.setText(rs.getString(3));
                uniqueid = rs.getInt(19);
                txtnic.setText(rs.getString(18));
                txtname.setText(rs.getString(20));
                txtnamewithinitials.setText(rs.getString(24));
                txtdob.setText(rs.getString(21));
                cmbSex.setSelectedItem(rs.getString(22));
                cmbcancantdrive.setSelectedItem(rs.getString(15));
                cmbmanualauto2.setSelectedItem(rs.getString(16));

                txtlicenno.setText(rs.getString(12));
                txtlicendate.setText(rs.getString(13));
                txtlicenvclass.setText(rs.getString(14));

                txtadress.setText(rs.getString(4));
                txttp1.setText(rs.getString(5));
                txttp2.setText(rs.getString(6));
                txttp3.setText(rs.getString(7));

                txtbarcode.setText(rs.getString(8));
                txtvehicleclass.setText(rs.getString(10));
                txtmedicalno.setText(rs.getString(11));
                txtNote.setText(rs.getString(25));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "division.division,\n"
                    + "police.police\n"
                    + "FROM\n"
                    + "customer_register\n"
                    + "INNER JOIN division ON customer_register.division_id = division.id\n"
                    + "INNER JOIN police ON customer_register.police_id = police.id\n"
                    + "WHERE\n"
                    + "customer_register.admission_no = '" + txtfindadmission.getText() + "'");
            if (rs.next()) {
                txtDivisionalSecretariat.setText(rs.getString(1));
                txtpolice.setText(rs.getString(2));

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadcmbdivision() {
        //  DefaultComboBoxModel dcbm=(DefaultComboBoxModel) cmbdivision.getModel();
        //  dcbm.removeAllElements();
        List<String> li = new ArrayList<String>();
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "division.id,\n"
                    + "division.division\n"
                    + "FROM\n"
                    + "division");

            while (rs.next()) {
                li.add(rs.getString(2));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        AutoCompleteDecorator.decorate(txtDivisionalSecretariat, li, true);
    }

    private void loadpolice() {
        List<String> li = new ArrayList<String>();
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "police.id,\n"
                    + "police.police\n"
                    + "FROM\n"
                    + "police");

            while (rs.next()) {
                li.add(rs.getString(2));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        AutoCompleteDecorator.decorate(txtpolice, li, true);
    }
}
