/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import com.ConstantData;
import com.Messages;
import com.userstatus;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import model.db2;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Lasitha Ranawaka
 */
public class customerRegisternew extends javax.swing.JDialog {

    public customerRegisternew(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        ImageIcon img = new ImageIcon("src/png/desktop.png");
        this.setIconImage(img.getImage());
        //  loadadmissiono();
        loadcmbdivision();
        loadpolice();
        txtnic.grabFocus();

    }

    int id = 0;
    //String sex = "";
    String canDriveOrNot = "";
    String manualOrAuto = "";
    int uniqueCustomerDetails_id;
    int customerId;
    int divisionId;
    int policeId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtmedicalno = new javax.swing.JFormattedTextField();
        cmbcancantdrive = new javax.swing.JComboBox();
        cmbmanualauto = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtlicenno = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtlicenvclass = new javax.swing.JFormattedTextField();
        txtlicendate = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        txtadmissiono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txttp2 = new javax.swing.JFormattedTextField();
        txtadress = new javax.swing.JTextField();
        txtbarcode = new javax.swing.JFormattedTextField();
        txttp3 = new javax.swing.JFormattedTextField();
        txtvehicleclass = new javax.swing.JFormattedTextField();
        txttp1 = new javax.swing.JFormattedTextField();
        txtnic = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtdob = new javax.swing.JFormattedTextField();
        cmbsex = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnamewithinitials = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDivisionalSecretariat = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtpolice = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Customer Register");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Details"));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel19.setText("Select");

        jLabel20.setText("Gear");

        jLabel15.setText("Medical No");

        txtmedicalno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmedicalnoActionPerformed(evt);
            }
        });
        txtmedicalno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmedicalnoKeyPressed(evt);
            }
        });

        cmbcancantdrive.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cannot Drive", "Can Drive" }));
        cmbcancantdrive.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbcancantdriveKeyPressed(evt);
            }
        });

        cmbmanualauto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Auto" }));
        cmbmanualauto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbmanualautoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbmanualauto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcancantdrive, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cmbcancantdrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cmbmanualauto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtmedicalno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtlicenno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicennoActionPerformed(evt);
            }
        });
        txtlicenno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicennoKeyPressed(evt);
            }
        });

        jLabel18.setText("Vehicle Class");

        jLabel16.setText("Old Licence No");

        jLabel17.setText("Licen Date");

        txtlicenvclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicenvclassActionPerformed(evt);
            }
        });
        txtlicenvclass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicenvclassKeyPressed(evt);
            }
        });

        try {
            txtlicendate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtlicendate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlicendateActionPerformed(evt);
            }
        });
        txtlicendate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicendateKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(txtlicenno, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(txtlicendate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(txtlicenvclass, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtlicenno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtlicendate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtlicenvclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtadmissiono.setEditable(false);

        jLabel8.setText("Adress");

        jLabel5.setText("Sex");

        jLabel14.setText("Vehicle Class");

        try {
            txttp2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttp2ActionPerformed(evt);
            }
        });
        txttp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttp2KeyPressed(evt);
            }
        });

        txtadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadressActionPerformed(evt);
            }
        });
        txtadress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtadressKeyPressed(evt);
            }
        });

        txtbarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarcodeActionPerformed(evt);
            }
        });
        txtbarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarcodeKeyPressed(evt);
            }
        });

        try {
            txttp3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttp3ActionPerformed(evt);
            }
        });
        txttp3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttp3KeyPressed(evt);
            }
        });

        txtvehicleclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvehicleclassActionPerformed(evt);
            }
        });
        txtvehicleclass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvehicleclassKeyPressed(evt);
            }
        });

        try {
            txttp1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txttp1.setText("000-0000000");
        txttp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttp1ActionPerformed(evt);
            }
        });
        txttp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttp1KeyPressed(evt);
            }
        });

        txtnic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnicKeyPressed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        txtname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtnameInputMethodTextChanged(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });

        jLabel11.setText("Tp3");

        jLabel2.setText("Nic");

        jLabel10.setText("Tp2");

        jLabel12.setText("Barcode");

        jLabel9.setText("Tp1");

        jLabel7.setText("Admission No");

        try {
            txtdob.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdob.setText("0000-00-00");
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        txtdob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdobKeyPressed(evt);
            }
        });

        cmbsex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        cmbsex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbsexKeyPressed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("DOB");

        jLabel6.setText("Name With Initials");

        txtnamewithinitials.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamewithinitialsKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbsex, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtnamewithinitials, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txttp1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txttp2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txttp3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtadmissiono, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtvehicleclass, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtadmissiono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtbarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtnamewithinitials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txttp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txttp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txttp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(txtadress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtvehicleclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Print use only", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12), new java.awt.Color(0, 255, 0))); // NOI18N

        jLabel13.setText("Divisional Secretariat :");

        txtDivisionalSecretariat.setText("Not found");
        txtDivisionalSecretariat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDivisionalSecretariatKeyPressed(evt);
            }
        });

        jLabel21.setText("Police station");

        txtpolice.setText("Not found");
        txtpolice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpoliceKeyPressed(evt);
            }
        });

        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("R");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("R");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("New");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDivisionalSecretariat, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(txtpolice, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtDivisionalSecretariat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(txtpolice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        submit();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnicKeyPressed
        if (evt.getKeyCode() == 10) {
            if (isNotIDAlreadyExistInDB()) {
                txtbarcode.grabFocus();

            }
            loaddetails();

        }
    }//GEN-LAST:event_txtnicKeyPressed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed

    }//GEN-LAST:event_txtnameActionPerformed

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed

    }//GEN-LAST:event_txtdobActionPerformed

    private void txtlicennoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicennoActionPerformed

    }//GEN-LAST:event_txtlicennoActionPerformed

    private void txtlicendateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicendateActionPerformed
        txtlicenvclass.grabFocus();
    }//GEN-LAST:event_txtlicendateActionPerformed

    private void txtlicenvclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlicenvclassActionPerformed

    }//GEN-LAST:event_txtlicenvclassActionPerformed

    private void txtadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadressActionPerformed

    }//GEN-LAST:event_txtadressActionPerformed

    private void txttp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttp1ActionPerformed

    }//GEN-LAST:event_txttp1ActionPerformed

    private void txttp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttp2ActionPerformed

    }//GEN-LAST:event_txttp2ActionPerformed

    private void txttp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttp3ActionPerformed

    }//GEN-LAST:event_txttp3ActionPerformed

    private void txtbarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarcodeActionPerformed

    }//GEN-LAST:event_txtbarcodeActionPerformed

    private void txtvehicleclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvehicleclassActionPerformed

    }//GEN-LAST:event_txtvehicleclassActionPerformed

    private void txtmedicalnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmedicalnoActionPerformed


    }//GEN-LAST:event_txtmedicalnoActionPerformed

    private void txtbarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarcodeKeyPressed
        if (evt.getKeyCode() == 10) {
            txtname.grabFocus();
        }
    }//GEN-LAST:event_txtbarcodeKeyPressed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtname.getText();
            String result = changecase.toUpperCase();
            txtname.setText(result);
            txtnamewithinitials.grabFocus();

        }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtdobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdobKeyPressed
        if (evt.getKeyCode() == 10) {

            cmbsex.grabFocus();
        }
    }//GEN-LAST:event_txtdobKeyPressed

    private void txttp3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttp3KeyPressed
        if (evt.getKeyCode() == 10) {
            txtvehicleclass.grabFocus();
        }
    }//GEN-LAST:event_txttp3KeyPressed

    private void txtlicenvclassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenvclassKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtlicenvclass.getText();
            String result = changecase.toUpperCase();
            txtlicenvclass.setText(result);
            txtDivisionalSecretariat.grabFocus();
            txtDivisionalSecretariat.selectAll();
        }
    }//GEN-LAST:event_txtlicenvclassKeyPressed

    private void txtmedicalnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedicalnoKeyPressed
        if (evt.getKeyCode() == 10) {
            txtlicenno.grabFocus();
        }
    }//GEN-LAST:event_txtmedicalnoKeyPressed

    private void txtlicennoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicennoKeyPressed
        if (evt.getKeyCode() == 10) {
            txtlicendate.grabFocus();
        }
    }//GEN-LAST:event_txtlicennoKeyPressed

    private void txtlicendateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicendateKeyPressed
        if (evt.getKeyCode() == 10) {
            txtlicenvclass.grabFocus();
        }
    }//GEN-LAST:event_txtlicendateKeyPressed

    private void txttp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttp1KeyPressed

        if (evt.getKeyCode() == 10) {
            txttp2.grabFocus();
        }

    }//GEN-LAST:event_txttp1KeyPressed

    private void txttp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttp2KeyPressed
        if (evt.getKeyCode() == 10) {
            txttp3.grabFocus();
        }
    }//GEN-LAST:event_txttp2KeyPressed

    private void txtvehicleclassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehicleclassKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtvehicleclass.getText();
            String result = changecase.toUpperCase();
            txtvehicleclass.setText(result);
            cmbcancantdrive.grabFocus();
        }
    }//GEN-LAST:event_txtvehicleclassKeyPressed

    private void cmbsexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbsexKeyPressed
        if (evt.getKeyCode() == 10) {
            txtadress.grabFocus();

        }
    }//GEN-LAST:event_cmbsexKeyPressed

    private void cmbcancantdriveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbcancantdriveKeyPressed
        if (evt.getKeyCode() == 10) {
            cmbmanualauto.grabFocus();

        }
    }//GEN-LAST:event_cmbcancantdriveKeyPressed

    private void cmbmanualautoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbmanualautoKeyPressed
        if (evt.getKeyCode() == 10) {
            txtmedicalno.grabFocus();

        }
    }//GEN-LAST:event_cmbmanualautoKeyPressed

    private void txtDivisionalSecretariatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDivisionalSecretariatKeyPressed
        if (evt.getKeyCode() == 10) {
            txtpolice.grabFocus();
            txtpolice.selectAll();
        }
    }//GEN-LAST:event_txtDivisionalSecretariatKeyPressed

    private void txtpoliceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpoliceKeyPressed
        if (evt.getKeyCode() == 10) {
            jButton1.grabFocus();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtpoliceKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        submit();
    }//GEN-LAST:event_jButton1KeyPressed

    private void txtnamewithinitialsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamewithinitialsKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtnamewithinitials.getText();
            String result = changecase.toUpperCase();
            txtnamewithinitials.setText(result);
            txtdob.grabFocus();
            txtdob.selectAll();

        }
    }//GEN-LAST:event_txtnamewithinitialsKeyPressed

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped

    }//GEN-LAST:event_txtnameKeyTyped

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased

    }//GEN-LAST:event_txtnameKeyReleased

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost

    }//GEN-LAST:event_txtnameFocusLost

    private void txtnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtnameInputMethodTextChanged

    }//GEN-LAST:event_txtnameInputMethodTextChanged

    private void txtadressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadressKeyPressed
        if (evt.getKeyCode() == 10) {
            String changecase = txtadress.getText();
            String result = changecase.toUpperCase();
            txtadress.setText(result);
            txttp1.grabFocus();
            txttp1.selectAll();

        }
    }//GEN-LAST:event_txtadressKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new customerRegisternew(ConstantData.home, false).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new division(null, false).setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadcmbdivision();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadpolice();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new police(null, false).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerRegisternew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerRegisternew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerRegisternew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerRegisternew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                customerRegisternew dialog = new customerRegisternew(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cmbcancantdrive;
    private javax.swing.JComboBox cmbmanualauto;
    private javax.swing.JComboBox cmbsex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtDivisionalSecretariat;
    private javax.swing.JTextField txtadmissiono;
    private javax.swing.JTextField txtadress;
    private javax.swing.JFormattedTextField txtbarcode;
    private javax.swing.JFormattedTextField txtdob;
    private javax.swing.JFormattedTextField txtlicendate;
    private javax.swing.JTextField txtlicenno;
    private javax.swing.JFormattedTextField txtlicenvclass;
    private javax.swing.JFormattedTextField txtmedicalno;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnamewithinitials;
    private javax.swing.JTextField txtnic;
    private javax.swing.JTextField txtpolice;
    private javax.swing.JFormattedTextField txttp1;
    private javax.swing.JFormattedTextField txttp2;
    private javax.swing.JFormattedTextField txttp3;
    private javax.swing.JFormattedTextField txtvehicleclass;
    // End of variables declaration//GEN-END:variables

    private void loadadmissiono() {
        //get id for admission no from customer register
        try {
            ResultSet rs = model.db.getData("SELECT MAX(id) FROM customer_register");
            if (rs.next()) {
                int i = rs.getInt(1);
                txtadmissiono.setText(String.valueOf(i + 5001));
                customerId = i + 5001;
                System.out.println(customerId);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        ///////////////////////////////////////////////////////////////////////////////////
    }

    private boolean isNotIDAlreadyExistInDB() {
        boolean bol = true;
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "uniquecustomerdetails.nic\n"
                    + "FROM\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "uniquecustomerdetails.nic = '" + txtnic.getText() + "'");
            if (rs.next()) {
                bol = false;
                Messages.errorjoption("This NIC Number Already Exist ! ");
                txtnic.grabFocus();
                txtnic.selectAll();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        return bol;
    }

    private void loaddetails() {
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "uniquecustomerdetails.id,\n"
                    + "uniquecustomerdetails.nic,\n"
                    + "uniquecustomerdetails.`name`,\n"
                    + "uniquecustomerdetails.dob,\n"
                    + "uniquecustomerdetails.sex,\n"
                    + "uniquecustomerdetails.`status`,\n"
                    + "uniquecustomerdetails.namewithinitial\n"
                    + "FROM\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "uniquecustomerdetails.nic = '" + txtnic.getText() + "'");
            if (rs.next()) {
                id = rs.getInt(1);
                System.out.println(id);
                txtname.setText(rs.getString(3));
                txtdob.setText(rs.getString(4));
                cmbsex.setSelectedItem(rs.getString(5));
                txtnamewithinitials.setText(rs.getString(7));
//                if (rs.getString(5).equals("Male")) {
//                    rbtnmale.setSelected(true);
//                } else if (rs.getString(5).equals("Female")) {
//                    rbtnfemale.setSelected(true);
//                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void submit() {
        boolean bol = true;
        //canDriveOrNot
//        if (rbtncandrive.isSelected()) {
//            canDriveOrNot = "Can Drive";
//        } else if (rbtncantdrive.isSelected()) {
//            canDriveOrNot = "Cannot Drive";
//        }

        ///////////////////////////////////////////////////////////////////////////////////
        //manualOrAuto
//        if (rbtnmanual.isSelected()) {
//            manualOrAuto = "Manual";
//        } else if (rbtnauto.isSelected()) {
//            manualOrAuto = "Auto";
//        }
        ///////////////////////////////////////////////////////////////////////////////////////
        //male female
//        if (rbtnmale.isSelected()) {
//            sex = "Male";
//
//        } else if (rbtnfemale.isSelected()) {
//            sex = "Female";
//        }
        ///////////////////////////////////////////////////////////////////////////////////////
        //get uniqueCustomerDetails_id
        try {
            ResultSet rs = model.db.getData("SELECT MAX(id) FROM uniquecustomerdetails");
            if (rs.next()) {
                uniqueCustomerDetails_id = rs.getInt(1) + 1;

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        ////////////////////////////////////////////////////////////////////////////////////////

        /////////////////////division id////////////////////////////////
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "division.id\n"
                    + "FROM\n"
                    + "division\n"
                    + "WHERE\n"
                    + "division.division = '" + txtDivisionalSecretariat.getText() + "'");
            if (rs.next()) {
                divisionId = rs.getInt(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //////////////////////end division id///////////////////////
        ////////////////////get police id/////////////////////////
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "police.id\n"
                    + "FROM\n"
                    + "police\n"
                    + "WHERE\n"
                    + "police.police = '" + txtpolice.getText() + "'");
            if (rs.next()) {
                policeId = rs.getInt(1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        //////////////////end police id////////////////////////
        loadadmissiono();
        if (txtnic.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the NIC!");
            txtnic.grabFocus();
            return;
        }
        if (txtname.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the Name!");
            txtname.grabFocus();
            return;

        }
        if (txtnamewithinitials.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the Name with initials!");
            txtname.grabFocus();
            return;

        }

        if (txttp1.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the TP1!");
            txttp1.grabFocus();
            return;

        }
        if (txtvehicleclass.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the Vehicle class!");
            txtvehicleclass.grabFocus();
            return;

        }
        if (txtdob.getText().isEmpty()) {
            com.Messages.errorjoption("Enter the DOB!");
            txtdob.grabFocus();
            return;

        } else {
            if (id == 0) {
                Connection con = db2.getconn();
                try {

                    //unique details send
                    model.db2.putData("INSERT INTO uniquecustomerdetails(nic,name,dob,sex,status,namewithinitial)values('" + txtnic.getText() + "',"
                            + "'" + txtname.getText().toUpperCase() + "','" + txtdob.getText() + "','" + cmbsex.getSelectedItem() + "','" + "New" + "',"
                            + "'" + txtnamewithinitials.getText().toUpperCase() + "')");

                    if (con != null) {
                        con.commit();

                    }

                    ////////////////////////////////
                    //repeat data
                    model.db2.putData("INSERT INTO customer_register(uniqueCustomerDetails_id,admission_no,adress,tp1,tp2,tp3,"
                            + "barcode,reg_date,vehicle_class,medicalNo,licenNo,licenDate,vclass,canDriveOrNot,manualOrAuto,"
                            + "status,nic,division_id,police_id)values('" + uniqueCustomerDetails_id + "','" + customerId + "','" + txtadress.getText().toUpperCase() + "',"
                            + "'" + txttp1.getText() + "','" + txttp2.getText() + "','" + txttp3.getText() + "','" + txtbarcode.getText() + "',"
                            + " NOW(),'" + txtvehicleclass.getText().toUpperCase() + "','" + txtmedicalno.getText() + "','" + txtlicenno.getText() + "',"
                            + "'" + txtlicendate.getText() + "','" + txtlicenvclass.getText().toUpperCase() + "','" + cmbcancantdrive.getSelectedItem() + "',"
                            + "'" + cmbmanualauto.getSelectedItem() + "','" + "new" + "','" + txtnic.getText() + "','" + divisionId + "','" + policeId + "')");

                    ///////////////////////////////////////////
                    //log
                    model.db2.putData("INSERT INTO log(date,description,username)values(NOW(),'" + "new user register" + "',"
                            + "'" + userstatus.LodUser + "')");

                    ////////////////////////////////////////////////////////////////////////
                    if (con != null) {
                        con.commit();

                    }
                    Messages.normaljoption("Data Saved!");
                } catch (SQLException ex) {
                    try {
                        bol = false;
                        com.Messages.warningjoption("Please Check Again! ");
                        //  db2.getconn().rollback();
                        System.out.println("rollbacked");
                        con.rollback();

                    } catch (SQLException ex1) {
                        Logger.getLogger(customerRegisternew.class.getName()).log(Level.SEVERE, null, ex1);
                    }
                    ex.printStackTrace();

                }

            } else {
                //Connection con=db2.getconn();
                try {
                    //unique details send
//                    model.db.putData("INSERT INTO uniquecustomerdetails(nic,name,dob,sex,status)values('" + txtnic.getText() + "',"
//                            + "'" + txtname.getText() + "','" + txtdob.getText() + "','" + sex + "','" + "New" + "')");

                    ////////////////////////////////
                    //repeat data
                    model.db.putData("INSERT INTO customer_register(uniqueCustomerDetails_id,admission_no,adress,tp1,tp2,tp3,"
                            + "barcode,reg_date,vehicle_class,medicalNo,licenNo,licenDate,vclass,canDriveOrNot,manualOrAuto,"
                            + "status,nic,division_id,police_id)values('" + id + "','" + customerId + "','" + txtadress.getText() + "',"
                            + "'" + txttp1.getText() + "','" + txttp2.getText() + "','" + txttp3.getText() + "','" + txtbarcode.getText() + "',"
                            + " NOW(),'" + txtvehicleclass.getText().toUpperCase() + "','" + txtmedicalno.getText() + "','" + txtlicenno.getText() + "',"
                            + "'" + txtlicendate.getText() + "','" + txtlicenvclass.getText().toUpperCase() + "','" + cmbcancantdrive.getSelectedItem() + "',"
                            + "'" + cmbmanualauto.getSelectedItem() + "','" + "new" + "','" + txtnic.getText() + "',division_id='" + divisionId + "',police_id='" + policeId + "')");

                    ///////////////////////////////////////////
                    //log
                    model.db.putData("INSERT INTO log(date,description,username)values(NOW(),'" + "new user register" + "',"
                            + "'" + userstatus.LodUser + "')");

                    ////////////////////////////////////////////////////////////////////////
//                      if(con!=null){
//                    con.commit();
//                    
//                    }
                    Messages.normaljoption("Data Saved!");
                } catch (SQLException ex) {

//                     try {
//                           //  db2.getconn().rollback();
//                         
//                         bol=false;
//                         com.Messages.warningjoption("Please Check Again! ");
//                         
//                           System.out.println("rollbacked");
//                           
//                           
//                           con.rollback();
//                           
//                          
//                       } catch (SQLException ex1) {
//                           Logger.getLogger(customerRegisternew.class.getName()).log(Level.SEVERE, null, ex1);
//                       }
                    //setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    ex.printStackTrace();
                }

            }
        }
        if (bol) {
            this.dispose();
            new customerRegisternew(null, false).setVisible(true);
            new downPayment(txtadmissiono.getText()).setVisible(true);

            printapplication();

        }

    }

    private void printapplication() {

        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            //JRTableModelDataSource dataSource;
            // dataSource = new JRTableModelDataSource(tbl_Gin.getModel());
            //String reportSource = "c:\\reports\\viewInvoice.jrxml";
            String reportSource = "src/reports/application.jrxml";
            Map<String, Object> params = new HashMap<String, Object>();

            params.put("nic", String.valueOf(txtnic.getText()));
            params.put("name", String.valueOf(txtname.getText()));
            params.put("dob", String.valueOf(txtdob.getText()));

            params.put("sex", String.valueOf(cmbsex.getSelectedItem()));
            params.put("adress", String.valueOf(txtadress.getText()));
            params.put("vclass", String.valueOf(txtvehicleclass.getText()));
            params.put("divisionals", String.valueOf(txtDivisionalSecretariat.getText()));
            params.put("police", String.valueOf(txtpolice.getText()));
            params.put("oldlicenNO", String.valueOf(txtlicenno.getText()));
            params.put("oldlicenIssuedate", String.valueOf(txtlicendate.getText()));
            params.put("oldlicenceVclass", String.valueOf(txtlicenvclass.getText()));
            params.put("admissionno", String.valueOf(txtadmissiono.getText()));

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params);

            // JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.viewReport(jasperPrint, false);
            JasperPrintManager.printReport(jasperPrint, true);

            // JasperPrintManager.printReport(jasperPrint, false);
            // this.dispose();
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } catch (Exception e) {
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            e.printStackTrace();
        }
    }

    private void loadcmbdivision() {
        //  DefaultComboBoxModel dcbm=(DefaultComboBoxModel) cmbdivision.getModel();
        //  dcbm.removeAllElements();
        List<String> li = new ArrayList<String>();
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "division.id,\n"
                    + "division.division\n"
                    + "FROM\n"
                    + "division");

            while (rs.next()) {
                li.add(rs.getString(2));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        AutoCompleteDecorator.decorate(txtDivisionalSecretariat, li, true);
    }

    private void loadpolice() {
        List<String> li = new ArrayList<String>();
        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "police.id,\n"
                    + "police.police\n"
                    + "FROM\n"
                    + "police");

            while (rs.next()) {
                li.add(rs.getString(2));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        AutoCompleteDecorator.decorate(txtpolice, li, true);
    }
}
