package viewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.Format;
import viewer.*;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.MultiSplitLayout;

/**
 *
 * @author Lasitha Ranawaka
 */
public class DSR5 extends javax.swing.JDialog {

    /**
     * Creates new form template
     */
    public DSR5(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtdate.grabFocus();
        txtdate.selectAll();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPracticalExamDetails = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtdate = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_pass_a = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_pass_b = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_pass_b1 = new javax.swing.JTextField();
        txt_pass_g = new javax.swing.JTextField();
        txt_pass_d = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_pass_ce = new javax.swing.JTextField();
        txt_fail_ce = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_fail_b1 = new javax.swing.JTextField();
        txt_fail_a = new javax.swing.JTextField();
        txt_fail_g = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_fail_d = new javax.swing.JTextField();
        txt_fail_b = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_avg_pass_ce = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_avg_pass_a = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_avg_pass_b = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_avg_pass_b1 = new javax.swing.JTextField();
        txt_avg_pass_g = new javax.swing.JTextField();
        txt_avg_pass_d = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_avg_fail_ce = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txt_avg_fail_b1 = new javax.swing.JTextField();
        txt_avg_fail_a = new javax.swing.JTextField();
        txt_avg_fail_g = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txt_avg_fail_d = new javax.swing.JTextField();
        txt_avg_fail_b = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DSR5");
        jLabel1.setOpaque(true);

        tblPracticalExamDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Admission No", "Barcode", "Name", "Pass", "Fail", "Absent"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPracticalExamDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblPracticalExamDetails);
        if (tblPracticalExamDetails.getColumnModel().getColumnCount() > 0) {
            tblPracticalExamDetails.getColumnModel().getColumn(0).setMinWidth(50);
            tblPracticalExamDetails.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel2.setText("Find by Date");

        try {
            txtdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdate.setText("2016-06-15");
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Summery of Result");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("No of Passed");

        jLabel5.setText("A");

        jLabel6.setText("B");

        txt_pass_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pass_bActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("No of Failed");

        jLabel10.setText("B1");

        jLabel11.setText("G");

        txt_pass_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pass_gActionPerformed(evt);
            }
        });

        jLabel12.setText("D");

        jLabel13.setText("CE");

        txt_pass_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pass_ceActionPerformed(evt);
            }
        });

        txt_fail_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fail_ceActionPerformed(evt);
            }
        });

        jLabel14.setText("B1");

        jLabel15.setText("G");

        jLabel16.setText("A");

        txt_fail_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fail_gActionPerformed(evt);
            }
        });

        jLabel17.setText("B");

        txt_fail_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fail_bActionPerformed(evt);
            }
        });

        jLabel18.setText("D");

        jLabel19.setText("CE");

        txt_avg_pass_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avg_pass_ceActionPerformed(evt);
            }
        });

        jLabel8.setText("A");

        jLabel9.setText("B");

        txt_avg_pass_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avg_pass_bActionPerformed(evt);
            }
        });

        jLabel20.setText("B1");

        jLabel21.setText("G");

        txt_avg_pass_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avg_pass_gActionPerformed(evt);
            }
        });

        jLabel22.setText("D");

        jLabel23.setText("CE");

        txt_avg_fail_ce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avg_fail_ceActionPerformed(evt);
            }
        });

        jLabel24.setText("B1");

        jLabel25.setText("G");

        jLabel26.setText("A");

        txt_avg_fail_g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avg_fail_gActionPerformed(evt);
            }
        });

        jLabel27.setText("B");

        txt_avg_fail_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_avg_fail_bActionPerformed(evt);
            }
        });

        jLabel28.setText("D");

        jLabel29.setText("CE");

        jLabel30.setText("Total");

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_pass_a, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_pass_b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txt_pass_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txt_pass_g, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(txt_pass_d, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txt_pass_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_avg_pass_a, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txt_avg_pass_b, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(txt_avg_pass_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(txt_avg_pass_g, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(txt_avg_pass_d, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(txt_avg_pass_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(txt_avg_fail_a, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(txt_avg_fail_b, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_avg_fail_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txt_avg_fail_g, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(txt_avg_fail_d, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_avg_fail_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel30)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(txt_fail_a, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txt_fail_b, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txt_fail_b1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txt_fail_g, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txt_fail_d, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(txt_fail_ce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pass_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_pass_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_pass_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_pass_ce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pass_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_pass_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txt_fail_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_fail_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel14)
                                                .addComponent(jLabel15))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txt_fail_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txt_fail_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txt_fail_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_fail_ce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_avg_pass_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_avg_pass_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_avg_pass_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_avg_pass_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_avg_pass_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_avg_pass_ce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel26)
                                        .addComponent(jLabel27))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_avg_fail_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_avg_fail_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_avg_fail_b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_avg_fail_g, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_avg_fail_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_avg_fail_ce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        find();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        find();
    }//GEN-LAST:event_txtdateActionPerformed

    private void txt_pass_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pass_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pass_bActionPerformed

    private void txt_pass_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pass_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pass_gActionPerformed

    private void txt_pass_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pass_ceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pass_ceActionPerformed

    private void txt_fail_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fail_ceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fail_ceActionPerformed

    private void txt_fail_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fail_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fail_gActionPerformed

    private void txt_fail_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fail_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fail_bActionPerformed

    private void txt_avg_pass_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avg_pass_ceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avg_pass_ceActionPerformed

    private void txt_avg_pass_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avg_pass_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avg_pass_bActionPerformed

    private void txt_avg_pass_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avg_pass_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avg_pass_gActionPerformed

    private void txt_avg_fail_ceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avg_fail_ceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avg_fail_ceActionPerformed

    private void txt_avg_fail_gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avg_fail_gActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avg_fail_gActionPerformed

    private void txt_avg_fail_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_avg_fail_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_avg_fail_bActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            JRTableModelDataSource dataSource;
             dataSource = new JRTableModelDataSource(tblPracticalExamDetails.getModel());
            //String reportSource = "c:\\reports\\viewInvoice.jrxml";
            String reportSource = "src/reports/dsr5.jrxml";
            Map<String, Object> params = new HashMap<String, Object>();

            params.put("date", String.valueOf(txtdate.getText()));
            params.put("pass_a", String.valueOf(txt_pass_a.getText()));
            params.put("pass_b", String.valueOf(txt_pass_b.getText()));
            params.put("pass_b1", String.valueOf(txt_pass_b1.getText()));
            params.put("pass_g", String.valueOf(txt_pass_g.getText()));
            params.put("pass_d", String.valueOf(txt_pass_d.getText()));
            params.put("pass_ce", String.valueOf(txt_pass_ce.getText()));
            
            params.put("avg_pass_a", String.valueOf(txt_avg_pass_a.getText()));
            params.put("avg_pass_b", String.valueOf(txt_avg_pass_b.getText()));
            params.put("avg_pass_b1", String.valueOf(txt_avg_pass_b1.getText()));
            params.put("avg_pass_g", String.valueOf(txt_avg_pass_g.getText()));
            params.put("avg_pass_d", String.valueOf(txt_avg_pass_d.getText()));
            params.put("avg_pass_ce", String.valueOf(txt_avg_pass_ce.getText()));
            
            params.put("fail_a", String.valueOf(txt_fail_a.getText()));
            params.put("fail_b", String.valueOf(txt_fail_b.getText()));
            params.put("fail_b1", String.valueOf(txt_fail_b1.getText()));
            params.put("fail_g", String.valueOf(txt_fail_g.getText()));
            params.put("fail_d", String.valueOf(txt_fail_d.getText()));
            params.put("fail_ce", String.valueOf(txt_fail_ce.getText()));
            
            params.put("avg_fail_a", String.valueOf(txt_avg_fail_a.getText()));
            params.put("avg_fail_b", String.valueOf(txt_avg_fail_b.getText()));
            params.put("avg_fail_b1", String.valueOf(txt_avg_fail_b1.getText()));
            params.put("avg_fail_g", String.valueOf(txt_avg_fail_g.getText()));
            params.put("avg_fail_d", String.valueOf(txt_avg_fail_d.getText()));
            params.put("avg_fail_ce", String.valueOf(txt_avg_fail_ce.getText()));
            
            
            params.put("total", String.valueOf(txt_total.getText()));
            
            
            
            
            
           
            

            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params,dataSource);

            // JasperViewer.viewReport(jasperPrint, false);
            JasperViewer.viewReport(jasperPrint, false);
//            JasperPrintManager.printReport(jasperPrint, true);

            // JasperPrintManager.printReport(jasperPrint, false);
            // this.dispose();
//            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        } catch (Exception e) {
//            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSR5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSR5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSR5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSR5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DSR5 dialog = new DSR5(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPracticalExamDetails;
    private javax.swing.JTextField txt_avg_fail_a;
    private javax.swing.JTextField txt_avg_fail_b;
    private javax.swing.JTextField txt_avg_fail_b1;
    private javax.swing.JTextField txt_avg_fail_ce;
    private javax.swing.JTextField txt_avg_fail_d;
    private javax.swing.JTextField txt_avg_fail_g;
    private javax.swing.JTextField txt_avg_pass_a;
    private javax.swing.JTextField txt_avg_pass_b;
    private javax.swing.JTextField txt_avg_pass_b1;
    private javax.swing.JTextField txt_avg_pass_ce;
    private javax.swing.JTextField txt_avg_pass_d;
    private javax.swing.JTextField txt_avg_pass_g;
    private javax.swing.JTextField txt_fail_a;
    private javax.swing.JTextField txt_fail_b;
    private javax.swing.JTextField txt_fail_b1;
    private javax.swing.JTextField txt_fail_ce;
    private javax.swing.JTextField txt_fail_d;
    private javax.swing.JTextField txt_fail_g;
    private javax.swing.JTextField txt_pass_a;
    private javax.swing.JTextField txt_pass_b;
    private javax.swing.JTextField txt_pass_b1;
    private javax.swing.JTextField txt_pass_ce;
    private javax.swing.JTextField txt_pass_d;
    private javax.swing.JTextField txt_pass_g;
    private javax.swing.JTextField txt_total;
    private javax.swing.JFormattedTextField txtdate;
    // End of variables declaration//GEN-END:variables

    private void loadtbl() {
//        DefaultTableModel dtm = (DefaultTableModel) tblWrittenExamDetails.getModel();
//        dtm.setRowCount(0);
//        try {
//            ResultSet rs = model.db.getData("SELECT\n"
//                    + "writtenexamresult.id,\n"
//                    + "customer_register.admission_no,\n"
//                    + "customer_register.nic,\n"
//                    + "writtenexamresult.examDate,\n"
//                    + "writtenexamresult.writtenResult,\n"
//                    + "writtenexamresult.passOrFail\n"
//                    + "\n"
//                    + "FROM\n"
//                    + "writtenexamresult ,\n"
//                    + "customer_register\n"
//                    + "WHERE\n"
//                    + "writtenexamresult.customer_register_id = customer_register.id\n"
//                    + "ORDER BY\n"
//                    + "customer_register.admission_no ASC");
//
//            while (rs.next()) {
//                String id = rs.getString(1);
//                String admno = rs.getString(2);
//                String nic = rs.getString(3);
//                String date = rs.getString(4);
//                String result = rs.getString(5);
//                String status = rs.getString(6);
//                Object arr[] = {id, admno, nic, date, result, status};
//                dtm.addRow(arr);
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }

    private void find() {
        DefaultTableModel dtm = (DefaultTableModel) tblPracticalExamDetails.getModel();
        dtm.setRowCount(0);

        int passAcount = 0;
        int passBcount = 0;
        int passB1count = 0;
        int passGcount = 0;
        int passDcount = 0;
        int passCEcount = 0;

        int failAcount = 0;
        int failBcount = 0;
        int failB1count = 0;
        int failGcount = 0;
        int failDcount = 0;
        int failCEcount = 0;

        try {
            ResultSet rs = model.db.getData("SELECT\n"
                    + "practicalexam.id,\n"//1
                    + "practicalexam.customer_register_id,\n"//2
                    + "practicalexam.examDate,\n"//3
                    + "practicalexam.a,\n"//4
                    + "practicalexam.a_pass_or_fail,\n"//5
                    + "practicalexam.b,\n"//6
                    + "practicalexam.b_pass_or_fail,\n"//7
                    + "practicalexam.bone,\n"//8
                    + "practicalexam.bone_pass_or_fail,\n"//9
                    + "practicalexam.g,\n"//10
                    + "practicalexam.g_pass_or_fail,\n"//11
                    + "practicalexam.d,\n"//12
                    + "practicalexam.d_pass_or_fail,\n"//13
                    + "practicalexam.ce,\n"//14
                    + "practicalexam.ce_pass_or_fail,\n"//15
                    + "customer_register.admission_no,\n"//16
                    + "customer_register.barcode,\n"//17
                    + "uniquecustomerdetails.namewithinitial\n"//18
                    + "FROM\n"
                    + "practicalexam ,\n"
                    + "customer_register ,\n"
                    + "uniquecustomerdetails\n"
                    + "WHERE\n"
                    + "practicalexam.examDate = '" + txtdate.getText() + "' AND\n"
                    + "practicalexam.customer_register_id = customer_register.id AND\n"
                    + "customer_register.uniqueCustomerDetails_id = uniquecustomerdetails.id\n"
                    + "ORDER BY\n"
                    + "customer_register.admission_no ASC");

            int a = 1;

            while (rs.next()) {
                String passa = "";
                String passb = "";
                String passb1 = "";
                String passg = "";
                String passd = "";
                String passce = "";
                /////////////
                String faila = "";
                String failb = "";
                String failb1 = "";
                String failg = "";
                String faild = "";
                String failce = "";
                ///////////////
                String absenta = "";
                String absentb = "";
                String absentb1 = "";
                String absentg = "";
                String absentd = "";
                String absentce = "";
                ////////////////

                String admno = rs.getString(16);
                String barcode = rs.getString(17);
                String name = rs.getString(18);

                if (rs.getString(5).equals("Pass")) {
                    passa = rs.getString(4);
                    passAcount++;
                }
                if (rs.getString(7).equals("Pass")) {
                    passb = rs.getString(6);
                    passBcount++;
                }
                if (rs.getString(9).equals("Pass")) {
                    passb1 = rs.getString(8);
                    passB1count++;
                }
                if (rs.getString(11).equals("Pass")) {
                    passg = rs.getString(10);
                    passGcount++;
                }
                if (rs.getString(13).equals("Pass")) {
                    passd = rs.getString(12);
                    passDcount++;
                }
                if (rs.getString(15).equals("Pass")) {
                    passce = rs.getString(14);
                    passCEcount++;
                }
                //////////////////////////

                if (rs.getString(5).equals("Fail")) {
                    faila = rs.getString(4);
                    failAcount++;
                }
                if (rs.getString(7).equals("Fail")) {
                    failb = rs.getString(6);
                    failBcount++;
                }
                if (rs.getString(9).equals("Fail")) {
                    failb1 = rs.getString(8);
                    failB1count++;
                }
                if (rs.getString(11).equals("Fail")) {
                    failg = rs.getString(10);
                    failGcount++;
                }
                if (rs.getString(13).equals("Fail")) {
                    faild = rs.getString(12);
                    failDcount++;
                }
                if (rs.getString(15).equals("Fail")) {
                    failce = rs.getString(14);
                    failCEcount++;
                }
                //////////////////////////
                if (rs.getString(5).equals("Absent")) {
                    absenta = rs.getString(4);

                }
                if (rs.getString(7).equals("Absent")) {
                    absentb = rs.getString(6);

                }
                if (rs.getString(9).equals("Absent")) {
                    absentb1 = rs.getString(8);

                }
                if (rs.getString(11).equals("Absent")) {
                    absentg = rs.getString(10);

                }
                if (rs.getString(13).equals("Absent")) {
                    absentd = rs.getString(12);

                }
                if (rs.getString(15).equals("Absent")) {
                    absentce = rs.getString(14);

                }

//                String absent = rs.getString(6);
                Object arr[] = {a, admno, barcode, name, passa + passb + passb1 + passg + passd + passce,
                    faila + failb + failb1 + failg + faild + failce, absenta + absentb + absentb1 + absentg + absentd + absentce};
                dtm.addRow(arr);
                a++;

            }

        } catch (Exception e) {
            e.printStackTrace();
        }

//        int b = 0;
//        for (int i = 0; i < tblPracticalExamDetails.getRowCount(); i++) {
//            
//            if (dtm.getValueAt(i, 4).toString().split("").equals("A")) {
//                b++;
//
//            }
//
//        }
//        txt_pass_a.setText("" + b);
        txt_pass_a.setText(""+passAcount);
        txt_pass_b.setText(""+passBcount);
        txt_pass_b1.setText(""+passB1count);
        txt_pass_g.setText(""+passGcount);
        txt_pass_d.setText(""+passDcount);
        txt_pass_ce.setText(""+passCEcount);
        
        txt_fail_a.setText(""+failAcount);
        txt_fail_b.setText(""+failBcount);
        txt_fail_b1.setText(""+failB1count);
        txt_fail_g.setText(""+failGcount);
        txt_fail_d.setText(""+failDcount);
        txt_fail_ce.setText(""+failCEcount);
        
        
        double total=passAcount+passBcount+passB1count+passGcount+passDcount+passCEcount+failAcount+failBcount+failB1count+failGcount+failDcount+failCEcount;
        txt_total.setText(""+total);
        
        txt_avg_pass_a.setText(""+ Format.nf2d.format((passAcount/total)*100) );
        txt_avg_pass_b.setText(""+ Format.nf2d.format((passBcount/total)*100) );
        txt_avg_pass_b1.setText(""+ Format.nf2d.format((passB1count/total)*100) );
        txt_avg_pass_g.setText(""+ Format.nf2d.format((passGcount/total)*100) );
        txt_avg_pass_d.setText(""+ Format.nf2d.format((passDcount/total)*100) );
        txt_avg_pass_ce.setText(""+ Format.nf2d.format((passCEcount/total)*100) );
//        System.out.println(""+ (passAcount/total)*100 );
        
        
        txt_avg_fail_a.setText(""+ Format.nf2d.format((failAcount/total)*100) );
        txt_avg_fail_b.setText(""+ Format.nf2d.format((failBcount/total)*100) );
        txt_avg_fail_b1.setText(""+ Format.nf2d.format((failB1count/total)*100) );
        txt_avg_fail_g.setText(""+ Format.nf2d.format((failGcount/total)*100) );
        txt_avg_fail_d.setText(""+ Format.nf2d.format((failDcount/total)*100) );
        txt_avg_fail_ce.setText(""+ Format.nf2d.format((failCEcount/total)*100) );
        
        
        
        
        
        
        
        System.out.println(passAcount + " " + passB1count + " " + passBcount + " " + passGcount + " " + passDcount + " " + passCEcount);
        System.out.println(failAcount + " " + failB1count + " " + failBcount + " " + failGcount + " " + failDcount + " " + failCEcount);

    }
}
